# A Primer on Python Data Structures
## 📌 Overview

##### Simple variables store one value at a time.

##### Data structures allow us to store many values in a single variable.

##### The different types — lists, dictionaries, tuples, NumPy arrays, and Pandas DataFrames — differ in: 
##### -what kind of information they store, 
##### -how memory-efficient they are, 
##### -and how we can access/change the data.

## Exercise 1: Lists

##### A list is like a container that can hold many values in order.
##### It is mutable, which means you can add, remove, or change items.
##### Written with square brackets [ ].
### Why use a List?
##### When you need to store multiple related values.
##### Example: student names, gene IDs, daily temperatures.

### Some Useful Functions for Using Lists
There are two types of syntax to consider: 
- **The function takes an item from a list as input**: In this case you should write something like `my_list.function()`. Note, these functions change the list in place. 
- **The function taks a list (iteratable) as an input**: In this case you should write something like `function(my_list)`. Note, it may be preferable to create a new list to make these modifications. 

1. **Appending and Extending:**
   - `append(item)`: Adds an item to the end of the list.
   - `extend(iterable)`: Extends the list by appending all the items from the iterable (e.g., another list).

2. **Inserting and Removing Elements:**
   - `insert(index, item)`: Inserts an item at a specified index.
   - `remove(item)`: Removes the first occurrence of an item.
   - `pop([index])`: Removes and returns an item at a given index (or the last item if index is not specified).

3. **Finding Elements:**
   - `index(item)`: Returns the index of the first occurrence of an item.
   - `count(item)`: Returns the number of times an item appears in the list.

4. **Sorting:**
   - `sorted(iteratable)`: Sorts the items of the list.

5. **Copying:**
   - `copy(iteratable)`: Returns a shallow copy of the list.

6. **Clearing:**
   - `clear(iteratable)`: Removes all items from the list.

7. **List Comprehensions:**
   - A concise way to create lists. Uses `for` or `if` statements to iteratively create a list. 
   - `my_list = [x**2 for x in range(1,6)]` creates a list called my_list and fills it iteratively with the squares of 1-6.
   - `my_list = [x**2 for x in range(1, 6) if x % 2 == 0]` creates a list called my_list and fills it with only the even squares of 1-6. The conditional: `x % 2 == 0`, is a modulo function. A modulo function takes a number and a divisor and returns the remainder. Here, it means: `if the remainder of the list number divided by 2 is equal to 0` it must be even, so we keep it in the list.  

8. **Slicing:**
   - Used for accessing a subset of list elements. Syntax: `list[start:stop:step]`. Where step is the interval size between each list element. 

9. **Conversion to/from Other Data Types:**
   - `list(iterable)`: Converts an iterable (like a tuple, string, set, or dictionary) to a list.
   - `str.join(iterable)`: Concatenates a list of strings into a single string, with elements separated by the specified separator.

10. **Length:**
    - `len(list)`: Returns the number of items in the list.ns the number of items in the list.


In [1]:
# A list of amino acids
amino_acids = ["Alanine", "Glycine", "Serine"]

# Accessing elements
print(amino_acids[0])   # first amino acid
print(amino_acids[-1])  # last amino acid

# Adding an amino acid
amino_acids.append("Cysteine")

# Changing an amino acid
amino_acids[1] = "Leucine"

print("Updated amino acid list:", amino_acids)


Alanine
Serine
Updated amino acid list: ['Alanine', 'Leucine', 'Serine', 'Cysteine']


### Try adding an item and changing an item to the list below getting it to match the desired (pay attention to the type of parenthesis they matter when diffrentiating between tuples and lists)

In [ ]:
# Step 1: Create the list
enzymes = ["Amylase", "Lipase", "Protease"]

# Step 2: Print the second enzyme
print(enzyme(1))
# Step 3: Add Catalase using append function


# Step 4: Replace Lipase with DNA Polymerase


# Step 5: Print updated list



##### Lipase 
##### updated list ['Amylase', 'DNA Polymerase', 'Protease', 'Catalase']


#### AI prompt
##### Instructions: Copy and paste the section titled some useful functions for using lists. 

##### I just pasted a guide called 'Some Useful Functions for Using Lists.' Please help me practice each list function step by step as a beginner. Start with the first function, explain what it does in simple terms, give me a short coding challenge, and check my answer before moving to the next one.

## Exercise 2: Dictionaries
##### A dictionary stores data in key–value pairs.
##### Think of it like a real dictionary: the word is the key, and the definition is the value.
##### Written with curly braces { }.
##### You look up a value by its key, not its position.
## Why use a Dictionary?
##### When you want fast lookups for information.
##### Example: mapping amino acid → molecular weight, or student ID → grade.

In [1]:
# Dictionary of enzyme → function
enzymes = {
    "Amylase": "Breaks down starch",
    "Lipase": "Breaks down fats",
    "Protease": "Breaks down proteins"
}

# Accessing values
print(enzymes["Amylase"])  

# Adding a new entry
enzymes["Catalase"] = "Breaks down hydrogen peroxide"

# Changing a value
enzymes["Lipase"] = "Helps digest fats"

print("Updated dictionary:", enzymes)


Breaks down starch
Updated dictionary: {'Amylase': 'Breaks down starch', 'Lipase': 'Helps digest fats', 'Protease': 'Breaks down proteins', 'Catalase': 'Breaks down hydrogen peroxide'}


In [13]:
# Dictionary of vitamin → function
vitamins = {
    "Vitamin A": "Supports vision and immune function",
    "Vitamin C": "Aids in collagen synthesis and antioxidant defense",
    "Vitamin D": "Regulates calcium absorption and bone health"
}

# Accessing values


# Adding a new entry


# Changing a value





### Desired outcome
##### Supports vision and immune function
##### Updated dictionary:{'Vitamin A': 'Supports vision and immune function', 'Vitamin C': 'Boosts immunity and acts as an antioxidant', 'Vitamin D': 'Regulates calcium absorption and bone health', 'Vitamin B12': 'Supports red blood cell formation and nerve function'}

## Exercise 3: NumPy Arrays

##### -NumPy is a core Python library used for scientific and numerical computing.

##### -It introduces the array, a data structure similar to a list but optimized for numerical data.

##### -NumPy arrays store elements of the same data type (e.g., all floats or all integers).

##### -Arrays allow fast, element-wise mathematical operations without using loops.

##### -They are more efficient and faster than Python lists, especially for large datasets.

##### -Common NumPy operations include:

######       -Calculating means, standard deviations, and sums

######       -Performing vector and matrix calculations

######        -Handling multi-dimensional data (e.g., 2D arrays for tables, 3D for image data)

## -Widely used in biochemistry, biology, and data analysis for:

#####        -Reaction rate or enzyme activity calculations

#####        -Spectrophotometer absorbance readings

#####        -Protein concentration and expression data

#####        -Statistical summaries of lab results

### Some Useful Functions for Using NumPy Arrays

NumPy is a fundamental package for scientific computing in Python. It provides a high-performance multidimensional array object and tools for working with these arrays.

1. **Creating Arrays:**
   - `np.array(list)`: Creates a NumPy array from a list or list of lists.
   - `np.zeros(shape)`: Creates an array filled with zeros.
   - `np.ones(shape)`: Creates an array filled with ones.
   - `np.arange(start, stop, step)`: Creates an array with values from `start` to `stop` with `step` increments.
   - `np.linspace(start, stop, num)`: Creates an array with `num` evenly spaced values over the specified interval.

2. **Array Attributes:**
   - `ndarray.shape`: Tuple of array dimensions.
   - `ndarray.size`: Number of elements in the array.
   - `ndarray.dtype`: Data type of the array elements.
   - `ndarray.ndim`: Number of array dimensions.

3. **Indexing and Slicing:**
   - `array[index]`: Accesses an element.
   - `array[start:stop:step]`: Slices the array.

4. **Reshaping and Transposing:**
   - `reshape(shape)`: Gives a new shape to an array without changing its data.
   - `transpose()`: Permute the dimensions of an array.

5. **Mathematical Operations:**
   - `np.add()`, `np.subtract()`, `np.multiply()`, `np.divide()`: Basic arithmetic operations.
   - `np.sqrt()`, `np.log()`, `np.exp()`: Square root, logarithm, and exponential.
   - `np.sin()`, `np.cos()`, `np.tan()`: Trigonometric functions.

6. **Aggregation Functions:**
   - `np.sum()`, `np.mean()`, `np.median()`: Summation, mean, and median.
   - `np.min()`, `np.max()`: Minimum and maximum.
   - `np.std()`: Standard deviation.

7. **Linear Algebra:**
   - `np.dot()`: Dot product of two arrays.
   - `np.linalg.inv()`: Inverse of a matrix.
   - `np.linalg.eig()`: Eigenvalues and eigenvectors of a matrix.

8. **Random Module:**
   - `np.random.rand()`: Random values in a given shape.
   - `np.random.randint()`: Random integers from a low to a high range.
9. **Comparisons:**
   - `np.equal()`, `np.greater()`, `np.less()`: Element-wise comparisons.

10. **Combining/Splitting:**
    - `np.concatenate()`, `np.vstack()`, `np.hstack()`: Combine arrays.
    - `np.split()`, `np.vsplit()`, `np.hsplit()`: Split arrays.

11. **Saving and Loading:**
    - `np.save()`, `np.load()`: Save and load arrays to and from disk.


In [23]:
# Some useful examples
import numpy as np
# Create a 1D array
my_list = [1,2,3,4,5]
array_1D = np.array(my_list)
print(array_1D)

# Do math operations on the array; This is a very useful property of arrays
print(array_1D * 2)

# Create a 2D array from two lists
first_list = [1,2,3,4,5]
second_list = [5,4,3,2,1]
array_2D = np.array([first_list, second_list]) # notice the use of []
print(array_2D)

[1 2 3 4 5]
[ 2  4  6  8 10]
[[1 2 3 4 5]
 [5 4 3 2 1]]


### AI prompts
##### Copy and paste the section 'Some Useful Functions for Using NumPy Arrays.' from above into chat gpt or another AI service then paste the prompt below. 
#####  I just pasted a guide called 'Some Useful Functions for Using NumPy Arrays.' Please help me practice each NumPy function step by step as a beginner. Start with the first function, explain what it does in simple terms, give me a short coding exercise, and check my answer before moving to the next one. Continue through all of the functions listed.

## Exercise 4: Pandas DataFrames

Pandas DataFrames are a fundamental tool in Python for data manipulation and analysi DataFrames are particularly useful for large multivariate datasets, such as gene expression fold change data, or single cell flow cytometry data. 

. Key features and uses include:

- **Tabular Data Representation**: DataFrames provide a 2D table structure with rows and columns, similar to Excel spreadsheets or SQL tables.
- **Heterogeneous Data Types**: Each column can hold different data types (e.g., int, float, string), making it ideal for real-world data.
- **Data Manipulation**: Offers extensive functionality for modifying and transforming data, including adding/removing columns, filtering rows, and handling missing values.
- **Data Analysis**: Facilitates data analysis with built-in functions for descriptive statistics, aggregation, and handling time-series data.
- **Integration with Other Libraries**: Seamlessly works with other libraries like NumPy, Matplotlib, and Scikit-learn for numerical computing, plotting, and machine learnin
- **Note**: Notice that the dataframes can be easily created from a dictionary, and that the dictionary keys become the column headers. The more practical way to create dataframes is to read them from a .csv or excel file. We'll cover that process in the File IO primer.g tasks.


### Some Useful Functions for Using Pandas DataFrames 

Pandas DataFrames offer a wide range of functions for data manipulation and analysis. Here are some commonly used functions:

- **head()**: Displays the first few rows of the DataFrame.
  df.head()

- **describe()**: Provides a summary of statistics for numerical columns.
  df.describe()

- **groupby()**: Groups data by specified columns, useful for aggregation operations.
  df.groupby('column_name').mean()

- **merge()**: Merges two DataFrames based on a common column.
  pd.merge(df1, df2, on='common_column')

- **pivot_table()**: Creates a pivot table for data summarization.
  df.pivot_table(values='value_column', index='row_column', columns='column_column')

- **fillna()**: Fills NA/NaN values using a specified method.
  df.fillna(method='ffill')

In [18]:
# Some useful examples
import pandas as pd

# Simulating gene expression data using a dictionary
gene_expression_data = {
    'gene': ['gene1', 'gene2', 'gene3', 'gene4', 'gene5'],
    'raw_expression_level': [20, 55, 35, 80, 45],
    'fold_change': [1, 2.5, -1, 3, .75]
}
gene_expression = pd.DataFrame(gene_expression_data)

# Displaying the first few rows of the DataFrame
print("print the first five rows of the dataframe:\n", gene_expression.head()) # note: the '\n' adds a new line to keep the output nice and neat

# Basic statistics for each gene
print("print a table of summary statistics\n", gene_expression.describe())

# Filtering genes with expression level above a threshold
high_expression = gene_expression[gene_expression['raw_expression_level'] > 50]
print(high_expression)

print the first five rows of the dataframe:
     gene  raw_expression_level  fold_change
0  gene1                    20         1.00
1  gene2                    55         2.50
2  gene3                    35        -1.00
3  gene4                    80         3.00
4  gene5                    45         0.75
print a table of summary statistics
        raw_expression_level  fold_change
count              5.000000     5.000000
mean              47.000000     1.250000
std               22.527761     1.581139
min               20.000000    -1.000000
25%               35.000000     0.750000
50%               45.000000     1.000000
75%               55.000000     2.500000
max               80.000000     3.000000
    gene  raw_expression_level  fold_change
1  gene2                    55          2.5
3  gene4                    80          3.0


In [20]:
# Some useful examples
import pandas as pd

# Simulating protein data using a dictionary
protein_data = {
    'protein_name': ['Hemoglobin', 'Insulin', 'Collagen', 'Myosin', 'Keratin'],
    'function': [
        'Transports oxygen in the blood',
        'Regulates blood glucose levels',
        'Provides structural support in connective tissues',
        'Enables muscle contraction',
        'Protects epithelial cells and forms hair and nails'
    ],
    'protein_type': ['Globular', 'Hormone', 'Fibrous', 'Fibrous', 'Fibrous']
}

# Creating a DataFrame from the dictionary

# Displaying the first few rows of the DataFrame

# Displaying basic statistics for text-based data

# Filtering proteins that are fibrous


### Desired outcome

### AI prompts
##### Copy and paste the section 'Some Useful Functions for Using Pandas DataFrames.' from above into chat gpt or another AI service then paste the prompt below. 
#####  I just pasted a guide called 'Some Useful Functions for Using Pandas DataFrames.' Please help me practice each pandas function step by step as a beginner. Start with the first function, explain what it does in simple terms, give me a short coding exercise using a small DataFrame, and check my answer before moving to the next one. Continue through all of the functions listed.